### ISSUE TITLE
Tóm lượt nội dung buổi họp Dự Án (01/03/17

### ISSUE THREAD

**Issue by baotnq** [vinaas/tasks#1]
### Nội dung
- Trao đổi về format chuẩn mà BA sẽ tổng hợp yêu cầu cho Module tính năng ở https://gitlab.com/eic-document/Tasks/issues/10
- thống nhất cách thực hiện dựa vào thông tin do BA tổng hợp
- quy trình hoạt động thực tế
  1. BA sẽ tổng hợp yêu cầu theo từng Module
  2. Các nhóm sẽ chủ động thực hiện dựa theo thông tin của BA. Nhóm quan trọng nhất là xây dựng Prototype (kết hợp giữa HTML và Aurelia) cho Phần mềm
  3. Dùng Prototype trao đổi với khách hàng, thống nhất chi tiết thực hiện , cập nhật trên chính Prototype.
  4. Lặp lại các bước 3 cho tới khi hoàn chỉnh Prototype đúng với yêu cầu
  4. Điều chỉnh cuốn chiếu từ HTML -> Aurelia ->  Back-end
  5. bàn giao hệ thống thực tế

### Công việc sắp tới
> Kết quả thực hiện cập nhật lên website trên github

> Soạn tài liệu tóm lược với ví dụ minh họa 

-  Vận dụng thực tế vào việc phát triển 2 Modules cơ bản
   - Quản lý Nhân Viên https://gitlab.com/eic-document/Tasks/issues/4
   - Quản lý Phòng Ban https://gitlab.com/eic-document/Tasks/issues/10

- ~~Tìm hiểu các công cụ để chuẩn hóa, tăng tốc thực hiện~~ (dời lại thực hiện sau)
  - NSwagStudio, https://github.com/NSwag/NSwag/wiki/NSwagStudio
  - Json Editor http://jeremydorn.com/json-editor/

**Comment by baotnq** [comment]
@gattadesmond @tungptvn @thinnv và thành chủ động tạo công việc mình sẽ thực hiện tiếp theo cho mình nghe

**Comment by baotnq** [comment]
các bạn tập trung thực hiện vào cuối tuần này (03-04) để áp dụng vào dự án EIC và Kiều Hối luôn

**Comment by thanhtdvn** [comment]
Anh @baotnq add em vào project eic-document với nha

**Comment by baotnq** [comment]
@thanhtdvn đã add vào eic-document rồi em, nhưng cái này chỉ làm prototype thôi, phân quyền cho em cũng đâu lam gì được đâu

**Comment by thanhtdvn** [comment]
E chưa có join vào ko có xem dc các issues bên trên á a @baotnq

**Comment by baotnq** [comment]
@thanhtdvn em chưa accept vào group, em vào link https://github.com/vinaas để accepts nghe

**Comment by thanhtdvn** [comment]
Acc của em vẫn chưa vào dc https://gitlab.com/eic-document/Tasks/issues/10 nha a @baotnq

**Comment by baotnq** [comment]
tài khoản gitlab.com của em là gì, để anh còn add vào
