### ISSUE TITLE
Xây dựng backend project cho dự án Kiều Hối

### ISSUE THREAD

**Issue by thanhtdvn** [vinaas/tasks#12]
> Dựa theo https://github.com/vinaas/tasks/issues/11

Tasks:

* [ ] Khởi tạo project
* [ ] Khởi tạo các thực thể: accounts, group, pertner,...
* [ ] Xây dựng services cho các thực thể
 - Account
 - Deposit Ticket
 - WithDraw Ticket
 - ...
* [ ] Build API project 
 - Account APIs
 - Deposit APIs
 - ...
* [ ] Hiện thực lớp DAL làm việc với Oracle db
* [ ] Tạo Service Call Packege Chứa Store Procedure và Function

**Comment by thanhtdvn** [comment]
@thinnv tạo task tương ứng, checkout source về https://gitlab.com/kieuhoi/kieuhoi-core rồi disscuss với Thành nha, Thành chỉ cho Thìn cái chỗ sẽ code trên solution này.

**Comment by thinnv** [comment]
Đã lấy Code về.
@thanhtdvn  giờ Thìn bỏ vào chỗ nào Vậy Thanh

**Comment by thanhtdvn** [comment]
Trong project kieuhoi.data nha @thinnv. Tạo ra các model class: ! Account, Group, Partner, DepositTicket,... 

Xong Thìn hiện thực các repository (kế thừa và bổ sung các interface) , gọi store procedure bên chị Dinh là dc (map kết quả tra ra từ store procedure với các model class ở trên)

**Comment by thinnv** [comment]
@thanhtdvn  Đã commit code Kết nối Oracle [tại đây](https://gitlab.com/kieuhoi/kieuhoi-core/commit/ca54b1434995b5b7b70b7aba281b8e52b36dd3cc)
Thành Review nhé.
Để có thể Run Project MVC5  connect Oracle Thành tham khảo cài đặt [tại đây](https://github.com/easywebhub/tasks/issues/78#issuecomment-287997547)
