### ISSUE TITLE
Mô tả sơ lược kiến trúc backend

### ISSUE THREAD

**Issue by thanhtdvn** [vinaas/tasks#15]
Dựa theo https://github.com/vinaas/tasks/issues/14

overview structures: folder & files structure at md format

/root
  |__ favourits   : // dùng để chứa phần favouris
  |   |__ Downloads
  |   |__ Desktops
  |__ Libraries  // thìn phụ trách phần này

Thực hiện tại wiki: https://gitlab.com/kieuhoi/kieuhoi-core/wikis/project-structure

Cc: @baotnq, @thinnv

**Comment by baotnq** [comment]
@thanhtdvn em mô tả chi tiết hơn công việc em làm nghe, hoặc ít nhất thì copy phần đã trao đôi bên kia qua, chứ đừng để trống không như vậy

**Comment by thanhtdvn** [comment]
Anh @baotnq, đã thực hiện xong mô tả cơ bản project structures tại https://gitlab.com/kieuhoi/kieuhoi-core/wikis/project-structure. Và sẽ tiếp tục update sau

**Comment by baotnq** [comment]
@thanhtdvn em đừng bỏ ở wiki như vậy, rời rạc và khó tìm thông tin sau này nghe.
Với thông tin quan trọng này, em hãy bỏ trong `README.md` để mọi người dễ biết.
Còn nếu README nhiều quá, thì em tách ra từng files chi tiết hơn, và gắn link trong Readme là được. 

Thống nhất cách như vậy nghe, đừng sử dụng wiki nữa.

**Comment by baotnq** [comment]
anh cũng sửa lại 1 vài chỗ cho format hiển thị đẹp hơn, https://gitlab.com/kieuhoi/kieuhoi-core/wikis/project-structure/history, nhưng do wiki không có `diff` rõ ràng như `repository` nên ko gửi em phần thay đổi để em xem được. tuy nhiên em tự xem và điều chỉnh nghe
