### ISSUE TITLE
Công việc tiếp theo sau buổi họp 25/3

### ISSUE THREAD

**Issue by tungptvn** [vinaas/tasks#16]
> Dựa theo [công việc](https://github.com/vinaas/tasks/issues/14)
- [x] viết tài liệu cho các bước tạo mới 1 modules chuẩn đã thống nhất.
- [ ] tạo danh sách modules của Kiều Hối: menu phải + bố cục source code trên gitlab

**Comment by tungptvn** [comment]
@baotnq `viết tài liệu cho các bước tạo mới 1 modules chuẩn đã thống nhất.` [documented](https://github.com/easywebhub/admincp-skeleton/blob/master/docs/huong-dan-them-modules.md)

**Comment by baotnq** [comment]
anh đọc sơ qua tài liệu, thấy khá rõ ràng và đầy đủ, làm rất tốt đó @tungptvn .
Tuy nhiên vẫn chưa thấy rõ cách xử lý cho từng trường hợp, ví dụ `create | edit` mô tả ở [đây](https://github.com/vinaas/tasks/wiki/Cách-xử-lý-cho-1-Module-của-dự-án-Web-Admin#xử-lý-khi-create--edit).

Em bổ sung tài liệu, với mỗi bước thực hiện nêu ra, thì phần code thực hiện là gì luôn nghe. Cập nhật vào phần mô tả trên cho việc thực hiện chi tiết này, nó là 1 phần con nằm trong phần "viết tài liệu cho ... " nghe.

**Comment by tungptvn** [comment]
@baotnq em mới cập nhật lại doc bổ xung thêm các trường hợp xử lý
