### ISSUE TITLE
Chuẩn bị lại project cho Thin hiện thực phần connect với Oracle trên backend project

### ISSUE THREAD

**Issue by thanhtdvn** [vinaas/tasks#17]
> Dựa theo https://github.com/vinaas/tasks/issues/14

* [x] review project connect oracle https://gitlab.com/kieuhoi/kieuhoi-core/issues/5
* [x] init unit test project cho solution https://gitlab.com/kieuhoi/kieuhoi-core/issues/6

Cc: @baotnq, @thinnv

**Comment by baotnq** [comment]
@thanhtdvn điều chỉnh thành dạng checklist cho từng công việc thực hiện nghe

**Comment by baotnq** [comment]
@thinnv  review phần việc trên của @thanhtdvn , xem có đáp ứng yêu cầu của em để phát triển độc lập nhưng vẫn kết nối được với phần của thành không nghe

**Comment by thinnv** [comment]
Phần core này ổn nha a Bảo. Phần Service thì dùng chung, Em có thể dùng UnitTest để test phần data lấy lên từ Oracle cũng được
