### ISSUE TITLE
Chuyển repository sang vinaas

### ISSUE THREAD

**Issue by baotnq** [vinaas/tasks#20]
### Mục đích
- để tránh nhầm lẫn, lộn xộn giữa dự án VinaAS và sản phẩm easyweb
- cần thì sau này fork trên cái gốc qua easywebhub vẫn được.

### Nội dung
- Chuyển easywebhub repositories sang vinaas
    - https://github.com/easywebhub/admin-pages-template   @gattadesmond làm
    - https://github.com/easywebhub/admincp-skeleton  @tungptvn 

- cách thực hiện
    - tạo mới repository trên vinaas 
    - đổi remote repository setting trỏ về repo mới
    - push toàn bộ lên repo moi
    - clone tất cả issue sang ở repo mới

- Sau khi chuyển xong, nếu review ổn thì mới xoá repository cũ đi

**Comment by baotnq** [comment]
@gattadesmond @tungptvn  đã thực hiện việc chuyển này chưa, hay vẫn muốn để nguyên như cũ?

**Comment by tungptvn** [comment]
@baotnq Em đã chuyển qua bên Vinaas rồi anh. https://github.com/vinaas/admincp-skeleton

**Comment by gattadesmond** [comment]
@baotnq e chuyển project build html qua vinass. https://github.com/vinaas/admin-page-template

**Comment by baotnq** [comment]
@tungptvn @gattadesmond các issues đang có cũng đã chuyển hết qua chưa các bạn, cũng như đã build `gh-pages` luôn chứ, nếu có thì add link vào phần mô tả của repository để preview cho nhanh nghe

**Comment by baotnq** [comment]
đã xong
