### ISSUE TITLE
Dựng web API, demo interface API module YeuCauHoanDoi, YeuCauCapNhatSoDu

### ISSUE THREAD

**Issue by thanhtdvn** [vinaas/tasks#22]
> Dựa theo https://github.com/vinaas/tasks/issues/19

API Links: http://apikieuhoi.easyadmincp.com

Thực hiện tại https://gitlab.com/kieuhoi/kieuhoi-core/issues/7

**Comment by thanhtdvn** [comment]
Anh @baotnq, em đã hoàn thành task này. Anh cập nhật nhé

**Comment by baotnq** [comment]
@thanhtdvn anh coi qua thấy ổn rồi em. Nhưng em điều chỉnh dùm anh

- [ ] sử dụng `apikieuhoi.vinaas.com` thay cho API link hiện tại nghe. Cho anh  thông tin github repo để anh điều chỉnh trên cloudflare
- [ ] refactor  đổi từ `Ticket` sang `Transactions` cho đồng nhất, sử dụng số nhiều thay vì số ít của đối tượng để đúng chuẩn restful nghe. 

Lưu ý cập nhật luôn @thinnv  để nắm thông tin và phối hợp với em hơn
