### ISSUE TITLE
Cách tạo dữ liệu mẫu (fake data) cho dự án

### ISSUE THREAD

**Issue by baotnq** [vinaas/tasks#9]
### Yêu Cầu
- Cần có bộ dữ liệu mẫu, cho các đối tượng và mối liên quan giữa chúng
- dữ liệu sinh ra nhanh chóng tự động và có thể chạy nhiều lần
- Áp dụng vào dự án Kiều Hối 
  - tìm cách sinh ra dữ liệu mẫu cho Yêu Cầu Hoán Đổi, Yêu Cầu Điều Chỉnh Số Dư của Kiều Hối
### Tài liệu
- tham khảo FakeIt và Couchbase
  - Phần 1 https://blog.couchbase.com/fakeit-series-generating-fake-data/
  - phần 2 https://blog.couchbase.com/fakeit-series-shared-data-dependencies/
  - các phần khác chắc sắp có
- lưu dữ liệu vào Couchbase để test luôn
### Các bước thực hiện
- THỰC HIỆN IMPORT STATIC FAKE DATA  VỚI FILE JSON CÓ  SẴN

   - FILE:  JSON

   - Bước 1: Vào Couchbase server Terminal
   - Bước 2: Sử dụng cú pháp: 
      $cbdocloader -n  <host>:<port> -b <bucket name> <source file> -u <user> -p <password>
      Ví dụ: $/opt/couchbase/bin/cbdocloader -n 127.0.0.1:8091 -b ecommerce  countries.json -u username -p 123456

![image](https://cloud.githubusercontent.com/assets/6780364/24319138/8bc8362c-1145-11e7-978b-351365c8df61.png)
- THỰC HIỆN DATA ĐỘNG TỪ FAKE IT
  - Install
    - npm install fakeit --save-dev  # or npm install fakeit --global
  - Thực hiện lệnh command để tạo data từ file yaml
   fakeit couchbase --server 127.0.0.1 --bucket ecommerce --count 100 --verbose models/

![image](https://cloud.githubusercontent.com/assets/6780364/24324103/ada62e26-11b2-11e7-8fb3-8de5535a3045.png)

Tham khảo data ở trang http://104.168.94.152:8091/ui/index.html#/query/workbench
lệnh query select * from `ecommerce`

@thinnv  phụ trách chính, cũng như trao đổi với @tungptvn  để cùng phối hợp nghe

**Comment by baotnq** [comment]
@thinnv ưu tiên xem phần này nghe, và tài liệu để giới thiệu cho các bạn

**Comment by thinnv** [comment]
- Cách tạo data static với  tools cbdocloader  với file json thì ok. Nhưng tạo data động với FakeIt với couchbase linux thì đang gặp vấn đề. 
Ngày mai e và bạn trong cty tiếp tục xử tiếp.
cc a @baotnq

**Comment by baotnq** [comment]
liệt kê các việc em đã làm, và sẽ làm nghe, phần nào xong thì cũng note luôn. 
Bám sát tutorials bên trên, đừng lang mang qua phần khác.

Ngoài ra fakeIT có thêm hướng dẫn series 3, em xem và cập nhật luôn.

**Comment by thinnv** [comment]
e đã update các bước thực hiện file json


cc a @baotnq

**Comment by baotnq** [comment]
@thinnv vậy em có thể dung fakeIT để sinh ra dữ liệu trên máy local được không, ra file JSON được chưa vậy . Rồi sau đó import vào couchbase. 
Lưu ý, cập nhật series 3 mới có trên blog couchbase fakeIT nghe

**Comment by thinnv** [comment]
a @baotnq  e đã cập nhật ở trên rồi nha.
Có thể thực hiện ở client khi cài FakeIT,  có update bên trên phân mô tả

**Comment by baotnq** [comment]
@thinnv  vậy theo hướng dẫn ở 3 series, em đã hoàn thành phần nào, tóm lượt trạng thái dùm anh nghe, ví dụ
- [ ] `trang thái` series 1, link kết quả
- [ ] `trang thái` series 2, link kết quả
- [ ] `trang thái` series 3, link kết quả

**Comment by baotnq** [comment]
@thinnv anh đã thêm phần Công việc thực hiện vào mô tả bên trên, sau này em cũng thực hiện như thế cho các issues khác nghe.
Ngoài ra link gitlab đang trỏ tới phần anh chưa được phân quyền, em nên move cái này qua https://gitlab.com/kieuhoi/kieuhoi-core để tiện chia sẻ sau này nghe

**Comment by thinnv** [comment]
- E đã chỉnh lại trên Gitlab dạng public, lý do viết trên gitlab là hôm trước github attach file bị lỗi . 
A xem lại thông tin nha.
Em thấy phần này Yêu cầu hoán đổi và tạo số dư cần tạo nhiều bảng danh mục nên e đưa ý kiến thế này:
 1. E sẽ rà sót lại các bảng danh mục mình cần theo file json của a [link](https://gitlab.com/kieuhoi/Tasks/blob/master/PhanTich/GiaoDichHoanDoiModel.md) 
sau đó yêu cầu a Phương và chị Dinh đổ data vào và e trả data tên Project Kieuhoi cho Thành.
2. TH chị Dinh và a Phương ko đáp ứng thì e sẽ viết các Model Fake Data sau đo cho vào Couchbase  nhé.
cc @baotnq , @thanhtdvn , @tungptvn

**Comment by baotnq** [comment]
@thinnv em vẫn move qua gitlab, repo chung như anh nói ở trên nghe, sau này chia sẻ dễ hơn là để trên repo cá nhân.

Phần fake data, sau khi em master mấy phần trên, sẽ sử dụng chính là để trả dữ liệu ở phần RestfulAPI trước, nên vừa xuất ra json fake data vừa cho import vào couchbase, tùy tình huống mà sử dụng cho tiện. 
Do đó cái 2 em vẫn tiến hành song song và chủ động so với cái 1 nghe, phần fake data đừng phụ thuộc vào bên chị Dinh, ảnh hưởng tới timeline bên chúng ta.
